name: release

on:
  push:
    tags:
    - "v*"

jobs:
  release-plugin:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11

    - name: Get tag
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build
      run: |
        sed -i "s/sentryDsn=/sentryDsn=${{secrets.INTELLIJ_PLUGIN_SENTRY_DSN}}/g" src/main/resources/config.properties
        sed -i -E "s/nhctlVersion=(.+)/nhctlVersion=${{ env.VERSION }}/g" src/main/resources/config.properties
        cat src/main/resources/config.properties
