name: release

on:
  push:
    tags:
    - "v*"

jobs:
  release-plugin:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11

    - name: Get tag
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "PLUGIN_VERSION=${GITHUB_REF#refs/*/}" | sed -E 's/v//g' >> $GITHUB_ENV
        echo "NHCTL_VERSION=${GITHUB_REF#refs/*/}" | sed 's/v//g' | sed -E 's/-202.+//g' >> $GITHUB_ENV

    - name: Build
      run: |
        sed -i "s/sentryDsn=/sentryDsn=${{secrets.INTELLIJ_PLUGIN_SENTRY_DSN}}/g" src/main/resources/config.properties
        sed -i -E "s/nhctlVersion=(.+)/nhctlVersion=${{ env.NHCTL_VERSION }}/g" src/main/resources/config.properties
        cat src/main/resources/config.properties
        sed -i -E "s/version=(.+)/version=${{ env.PLUGIN_VERSION }}/g" gradle.properties
        cat gradle.properties
